---

- name: get nginx apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: set up nginx apt repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://nginx.org/packages/ubuntu/ xenial nginx
    - deb-src http://nginx.org/packages/ubuntu/ xenial nginx

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: remove default nginx configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - stop nginx
    - start nginx

- name: copy qiime2.org certs
  copy:
    src: "{{ item }}"
    dest: /etc/ssl
  with_items:
    - "*.qiime2.org.chained.crt"
    - "*.qiime2.org.key"

- name: copy nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - stop nginx
    - start nginx
